import '../models/payment_models.dart';

class PaymentRegionService {
  static const countries = [
    PaymentCountry(
      name: 'Algeria',
      region: 'Africa',
      isoCode: 'DZ',
      dialCode: '+213',
      currencyCode: 'DZD',
      usdExchangeRate: 134.0,
      localTransferAgents: ['BaridiMob', 'CIB', 'Edahabia'],
    ),
    PaymentCountry(
      name: 'Angola',
      region: 'Africa',
      isoCode: 'AO',
      dialCode: '+244',
      currencyCode: 'AOA',
      usdExchangeRate: 920.0,
      localTransferAgents: ['Unitel Money', 'Multicaixa Express'],
    ),
    PaymentCountry(
      name: 'Benin',
      region: 'Africa',
      isoCode: 'BJ',
      dialCode: '+229',
      currencyCode: 'XOF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['MTN MoMo', 'Moov Money'],
    ),
    PaymentCountry(
      name: 'Botswana',
      region: 'Africa',
      isoCode: 'BW',
      dialCode: '+267',
      currencyCode: 'BWP',
      usdExchangeRate: 13.7,
      localTransferAgents: ['Orange Money', 'MyZaka', 'Smega'],
    ),
    PaymentCountry(
      name: 'Burkina Faso',
      region: 'Africa',
      isoCode: 'BF',
      dialCode: '+226',
      currencyCode: 'XOF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Orange Money', 'Moov Money'],
    ),
    PaymentCountry(
      name: 'Burundi',
      region: 'Africa',
      isoCode: 'BI',
      dialCode: '+257',
      currencyCode: 'BIF',
      usdExchangeRate: 2860.0,
      localTransferAgents: ['Lumicash', 'EcoCash'],
    ),
    PaymentCountry(
      name: 'Cabo Verde',
      region: 'Africa',
      isoCode: 'CV',
      dialCode: '+238',
      currencyCode: 'CVE',
      usdExchangeRate: 102.0,
      localTransferAgents: ['Vinti4', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Cameroon',
      region: 'Africa',
      isoCode: 'CM',
      dialCode: '+237',
      currencyCode: 'XAF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['MTN MoMo', 'Orange Money'],
    ),
    PaymentCountry(
      name: 'Central African Republic',
      region: 'Africa',
      isoCode: 'CF',
      dialCode: '+236',
      currencyCode: 'XAF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Orange Money', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Chad',
      region: 'Africa',
      isoCode: 'TD',
      dialCode: '+235',
      currencyCode: 'XAF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Airtel Money', 'Tigo Cash'],
    ),
    PaymentCountry(
      name: 'Comoros',
      region: 'Africa',
      isoCode: 'KM',
      dialCode: '+269',
      currencyCode: 'KMF',
      usdExchangeRate: 455.0,
      localTransferAgents: ['Holo', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Cote d\'Ivoire',
      region: 'Africa',
      isoCode: 'CI',
      dialCode: '+225',
      currencyCode: 'XOF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Orange Money', 'MTN MoMo', 'Moov Money', 'Wave'],
    ),
    PaymentCountry(
      name: 'Democratic Republic of the Congo',
      region: 'Africa',
      isoCode: 'CD',
      dialCode: '+243',
      currencyCode: 'CDF',
      usdExchangeRate: 2850.0,
      localTransferAgents: ['M-Pesa', 'Airtel Money', 'Orange Money'],
    ),
    PaymentCountry(
      name: 'Djibouti',
      region: 'Africa',
      isoCode: 'DJ',
      dialCode: '+253',
      currencyCode: 'DJF',
      usdExchangeRate: 178.0,
      localTransferAgents: ['D-Money', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Egypt',
      region: 'Africa',
      isoCode: 'EG',
      dialCode: '+20',
      currencyCode: 'EGP',
      usdExchangeRate: 47.3,
      localTransferAgents: ['Vodafone Cash', 'Orange Cash', 'Etisalat Cash'],
    ),
    PaymentCountry(
      name: 'Equatorial Guinea',
      region: 'Africa',
      isoCode: 'GQ',
      dialCode: '+240',
      currencyCode: 'XAF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Muni Dinero', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Eritrea',
      region: 'Africa',
      isoCode: 'ER',
      dialCode: '+291',
      currencyCode: 'ERN',
      usdExchangeRate: 15.0,
      localTransferAgents: ['Bank transfer', 'Cash pickup'],
    ),
    PaymentCountry(
      name: 'Eswatini',
      region: 'Africa',
      isoCode: 'SZ',
      dialCode: '+268',
      currencyCode: 'SZL',
      usdExchangeRate: 18.9,
      localTransferAgents: ['MTN MoMo', 'e-Mali'],
    ),
    PaymentCountry(
      name: 'Ethiopia',
      region: 'Africa',
      isoCode: 'ET',
      dialCode: '+251',
      currencyCode: 'ETB',
      usdExchangeRate: 57.0,
      localTransferAgents: ['Telebirr', 'M-Pesa', 'HelloCash'],
    ),
    PaymentCountry(
      name: 'Gabon',
      region: 'Africa',
      isoCode: 'GA',
      dialCode: '+241',
      currencyCode: 'XAF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Airtel Money', 'Moov Money'],
    ),
    PaymentCountry(
      name: 'Gambia',
      region: 'Africa',
      isoCode: 'GM',
      dialCode: '+220',
      currencyCode: 'GMD',
      usdExchangeRate: 68.0,
      localTransferAgents: ['QMoney', 'Afrimoney'],
    ),
    PaymentCountry(
      name: 'Ghana',
      region: 'Africa',
      isoCode: 'GH',
      dialCode: '+233',
      currencyCode: 'GHS',
      usdExchangeRate: 12.8,
      localTransferAgents: ['MTN MoMo', 'Telecel Cash', 'AirtelTigo Money'],
    ),
    PaymentCountry(
      name: 'Guinea',
      region: 'Africa',
      isoCode: 'GN',
      dialCode: '+224',
      currencyCode: 'GNF',
      usdExchangeRate: 8600.0,
      localTransferAgents: ['Orange Money', 'MTN MoMo'],
    ),
    PaymentCountry(
      name: 'Guinea-Bissau',
      region: 'Africa',
      isoCode: 'GW',
      dialCode: '+245',
      currencyCode: 'XOF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Orange Money', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Kenya',
      region: 'Africa',
      isoCode: 'KE',
      dialCode: '+254',
      currencyCode: 'KES',
      usdExchangeRate: 131.5,
      localTransferAgents: ['M-Pesa', 'Airtel Money', 'T-Kash'],
    ),
    PaymentCountry(
      name: 'Lesotho',
      region: 'Africa',
      isoCode: 'LS',
      dialCode: '+266',
      currencyCode: 'LSL',
      usdExchangeRate: 18.9,
      localTransferAgents: ['M-Pesa', 'EcoCash'],
    ),
    PaymentCountry(
      name: 'Liberia',
      region: 'Africa',
      isoCode: 'LR',
      dialCode: '+231',
      currencyCode: 'LRD',
      usdExchangeRate: 190.0,
      localTransferAgents: ['Orange Money', 'Lonestar Cell MTN Mobile Money'],
    ),
    PaymentCountry(
      name: 'Libya',
      region: 'Africa',
      isoCode: 'LY',
      dialCode: '+218',
      currencyCode: 'LYD',
      usdExchangeRate: 4.8,
      localTransferAgents: ['Sadad', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Madagascar',
      region: 'Africa',
      isoCode: 'MG',
      dialCode: '+261',
      currencyCode: 'MGA',
      usdExchangeRate: 4500.0,
      localTransferAgents: ['MVola', 'Orange Money', 'Airtel Money'],
    ),
    PaymentCountry(
      name: 'Malawi',
      region: 'Africa',
      isoCode: 'MW',
      dialCode: '+265',
      currencyCode: 'MWK',
      usdExchangeRate: 1730.0,
      localTransferAgents: ['Airtel Money', 'TNM Mpamba'],
    ),
    PaymentCountry(
      name: 'Mali',
      region: 'Africa',
      isoCode: 'ML',
      dialCode: '+223',
      currencyCode: 'XOF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Orange Money', 'Moov Money'],
    ),
    PaymentCountry(
      name: 'Mauritania',
      region: 'Africa',
      isoCode: 'MR',
      dialCode: '+222',
      currencyCode: 'MRU',
      usdExchangeRate: 39.5,
      localTransferAgents: ['Bankily', 'Masrvi'],
    ),
    PaymentCountry(
      name: 'Mauritius',
      region: 'Africa',
      isoCode: 'MU',
      dialCode: '+230',
      currencyCode: 'MUR',
      usdExchangeRate: 46.0,
      localTransferAgents: ['MauCAS', 'Juice', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Morocco',
      region: 'Africa',
      isoCode: 'MA',
      dialCode: '+212',
      currencyCode: 'MAD',
      usdExchangeRate: 10.0,
      localTransferAgents: ['Cash Plus', 'Wafacash', 'Orange Money'],
    ),
    PaymentCountry(
      name: 'Mozambique',
      region: 'Africa',
      isoCode: 'MZ',
      dialCode: '+258',
      currencyCode: 'MZN',
      usdExchangeRate: 64.0,
      localTransferAgents: ['M-Pesa', 'mKesh', 'e-Mola'],
    ),
    PaymentCountry(
      name: 'Namibia',
      region: 'Africa',
      isoCode: 'NA',
      dialCode: '+264',
      currencyCode: 'NAD',
      usdExchangeRate: 18.9,
      localTransferAgents: ['PayToday', 'BlueWallet', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Niger',
      region: 'Africa',
      isoCode: 'NE',
      dialCode: '+227',
      currencyCode: 'XOF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Airtel Money', 'Moov Money'],
    ),
    PaymentCountry(
      name: 'Nigeria',
      region: 'Africa',
      isoCode: 'NG',
      dialCode: '+234',
      currencyCode: 'NGN',
      usdExchangeRate: 1475.0,
      localTransferAgents: ['OPay', 'PalmPay', 'Paga', 'MoMo PSB'],
    ),
    PaymentCountry(
      name: 'Republic of the Congo',
      region: 'Africa',
      isoCode: 'CG',
      dialCode: '+242',
      currencyCode: 'XAF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Airtel Money', 'MTN MoMo'],
    ),
    PaymentCountry(
      name: 'Rwanda',
      region: 'Africa',
      isoCode: 'RW',
      dialCode: '+250',
      currencyCode: 'RWF',
      usdExchangeRate: 1290.0,
      localTransferAgents: ['MTN MoMo', 'Airtel Money'],
    ),
    PaymentCountry(
      name: 'Sao Tome and Principe',
      region: 'Africa',
      isoCode: 'ST',
      dialCode: '+239',
      currencyCode: 'STN',
      usdExchangeRate: 22.5,
      localTransferAgents: ['Dobra24', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Senegal',
      region: 'Africa',
      isoCode: 'SN',
      dialCode: '+221',
      currencyCode: 'XOF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['Wave', 'Orange Money', 'Free Money'],
    ),
    PaymentCountry(
      name: 'Seychelles',
      region: 'Africa',
      isoCode: 'SC',
      dialCode: '+248',
      currencyCode: 'SCR',
      usdExchangeRate: 13.5,
      localTransferAgents: [
        'Seychelles Electronic Funds Transfer',
        'Bank transfer'
      ],
    ),
    PaymentCountry(
      name: 'Sierra Leone',
      region: 'Africa',
      isoCode: 'SL',
      dialCode: '+232',
      currencyCode: 'SLE',
      usdExchangeRate: 22.5,
      localTransferAgents: ['Orange Money', 'Africell Money'],
    ),
    PaymentCountry(
      name: 'Somalia',
      region: 'Africa',
      isoCode: 'SO',
      dialCode: '+252',
      currencyCode: 'SOS',
      usdExchangeRate: 571.0,
      localTransferAgents: ['EVC Plus', 'Zaad', 'Sahal'],
    ),
    PaymentCountry(
      name: 'South Africa',
      region: 'Africa',
      isoCode: 'ZA',
      dialCode: '+27',
      currencyCode: 'ZAR',
      usdExchangeRate: 18.9,
      localTransferAgents: ['Mukuru', 'Ozow', 'Instant EFT', 'eWallet'],
    ),
    PaymentCountry(
      name: 'South Sudan',
      region: 'Africa',
      isoCode: 'SS',
      dialCode: '+211',
      currencyCode: 'SSP',
      usdExchangeRate: 1300.0,
      localTransferAgents: ['m-GURUSH', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Sudan',
      region: 'Africa',
      isoCode: 'SD',
      dialCode: '+249',
      currencyCode: 'SDG',
      usdExchangeRate: 600.0,
      localTransferAgents: ['Bankak', 'Cashi', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Tanzania',
      region: 'Africa',
      isoCode: 'TZ',
      dialCode: '+255',
      currencyCode: 'TZS',
      usdExchangeRate: 2550.0,
      localTransferAgents: ['M-Pesa', 'Tigo Pesa', 'Airtel Money', 'HaloPesa'],
    ),
    PaymentCountry(
      name: 'Togo',
      region: 'Africa',
      isoCode: 'TG',
      dialCode: '+228',
      currencyCode: 'XOF',
      usdExchangeRate: 605.0,
      localTransferAgents: ['TMoney', 'Flooz'],
    ),
    PaymentCountry(
      name: 'Tunisia',
      region: 'Africa',
      isoCode: 'TN',
      dialCode: '+216',
      currencyCode: 'TND',
      usdExchangeRate: 3.1,
      localTransferAgents: ['D17', 'Flouci', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Uganda',
      region: 'Africa',
      isoCode: 'UG',
      dialCode: '+256',
      currencyCode: 'UGX',
      usdExchangeRate: 3880.0,
      localTransferAgents: ['MTN MoMo', 'Airtel Money'],
    ),
    PaymentCountry(
      name: 'Zambia',
      region: 'Africa',
      isoCode: 'ZM',
      dialCode: '+260',
      currencyCode: 'ZMW',
      usdExchangeRate: 26.0,
      localTransferAgents: ['MTN MoMo', 'Airtel Money', 'Zamtel Kwacha'],
    ),
    PaymentCountry(
      name: 'Zimbabwe',
      region: 'Africa',
      isoCode: 'ZW',
      dialCode: '+263',
      currencyCode: 'ZWL',
      usdExchangeRate: 322.0,
      localTransferAgents: ['EcoCash', 'OneMoney', 'Telecash'],
    ),
    PaymentCountry(
      name: 'Antigua and Barbuda',
      region: 'North America',
      isoCode: 'AG',
      dialCode: '+1',
      currencyCode: 'XCD',
      usdExchangeRate: 2.7,
      localTransferAgents: ['Bank transfer', 'Cash pickup'],
    ),
    PaymentCountry(
      name: 'Bahamas',
      region: 'North America',
      isoCode: 'BS',
      dialCode: '+1',
      currencyCode: 'BSD',
      usdExchangeRate: 1.0,
      localTransferAgents: ['Sand Dollar', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Barbados',
      region: 'North America',
      isoCode: 'BB',
      dialCode: '+1',
      currencyCode: 'BBD',
      usdExchangeRate: 2.0,
      localTransferAgents: ['mMoney', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Belize',
      region: 'North America',
      isoCode: 'BZ',
      dialCode: '+501',
      currencyCode: 'BZD',
      usdExchangeRate: 2.0,
      localTransferAgents: ['DigiWallet', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Canada',
      region: 'North America',
      isoCode: 'CA',
      dialCode: '+1',
      currencyCode: 'CAD',
      usdExchangeRate: 1.36,
      localTransferAgents: ['Interac e-Transfer', 'EFT'],
    ),
    PaymentCountry(
      name: 'Costa Rica',
      region: 'North America',
      isoCode: 'CR',
      dialCode: '+506',
      currencyCode: 'CRC',
      usdExchangeRate: 520.0,
      localTransferAgents: ['SINPE Movil', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Cuba',
      region: 'North America',
      isoCode: 'CU',
      dialCode: '+53',
      currencyCode: 'CUP',
      usdExchangeRate: 24.0,
      localTransferAgents: ['Transfermovil', 'EnZona'],
    ),
    PaymentCountry(
      name: 'Dominica',
      region: 'North America',
      isoCode: 'DM',
      dialCode: '+1',
      currencyCode: 'XCD',
      usdExchangeRate: 2.7,
      localTransferAgents: ['Bank transfer', 'Cash pickup'],
    ),
    PaymentCountry(
      name: 'Dominican Republic',
      region: 'North America',
      isoCode: 'DO',
      dialCode: '+1',
      currencyCode: 'DOP',
      usdExchangeRate: 59.0,
      localTransferAgents: ['tPago', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'El Salvador',
      region: 'North America',
      isoCode: 'SV',
      dialCode: '+503',
      currencyCode: 'USD',
      usdExchangeRate: 1.0,
      localTransferAgents: ['Tigo Money', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Grenada',
      region: 'North America',
      isoCode: 'GD',
      dialCode: '+1',
      currencyCode: 'XCD',
      usdExchangeRate: 2.7,
      localTransferAgents: ['Bank transfer', 'Cash pickup'],
    ),
    PaymentCountry(
      name: 'Guatemala',
      region: 'North America',
      isoCode: 'GT',
      dialCode: '+502',
      currencyCode: 'GTQ',
      usdExchangeRate: 7.8,
      localTransferAgents: ['Tigo Money', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Haiti',
      region: 'North America',
      isoCode: 'HT',
      dialCode: '+509',
      currencyCode: 'HTG',
      usdExchangeRate: 132.0,
      localTransferAgents: ['MonCash', 'NatCash'],
    ),
    PaymentCountry(
      name: 'Honduras',
      region: 'North America',
      isoCode: 'HN',
      dialCode: '+504',
      currencyCode: 'HNL',
      usdExchangeRate: 24.7,
      localTransferAgents: ['Tigo Money', 'Tengo'],
    ),
    PaymentCountry(
      name: 'Jamaica',
      region: 'North America',
      isoCode: 'JM',
      dialCode: '+1',
      currencyCode: 'JMD',
      usdExchangeRate: 155.0,
      localTransferAgents: ['JN Money', 'VM Money Transfer', 'Lynk'],
    ),
    PaymentCountry(
      name: 'Mexico',
      region: 'North America',
      isoCode: 'MX',
      dialCode: '+52',
      currencyCode: 'MXN',
      usdExchangeRate: 16.7,
      localTransferAgents: ['CoDi', 'SPEI', 'OXXO Pay'],
    ),
    PaymentCountry(
      name: 'Nicaragua',
      region: 'North America',
      isoCode: 'NI',
      dialCode: '+505',
      currencyCode: 'NIO',
      usdExchangeRate: 36.6,
      localTransferAgents: ['Tigo Money', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'Panama',
      region: 'North America',
      isoCode: 'PA',
      dialCode: '+507',
      currencyCode: 'PAB',
      usdExchangeRate: 1.0,
      localTransferAgents: ['Yappy', 'ACH Express', 'Nequi'],
    ),
    PaymentCountry(
      name: 'Saint Kitts and Nevis',
      region: 'North America',
      isoCode: 'KN',
      dialCode: '+1',
      currencyCode: 'XCD',
      usdExchangeRate: 2.7,
      localTransferAgents: ['Bank transfer', 'Cash pickup'],
    ),
    PaymentCountry(
      name: 'Saint Lucia',
      region: 'North America',
      isoCode: 'LC',
      dialCode: '+1',
      currencyCode: 'XCD',
      usdExchangeRate: 2.7,
      localTransferAgents: ['Bank transfer', 'Cash pickup'],
    ),
    PaymentCountry(
      name: 'Saint Vincent and the Grenadines',
      region: 'North America',
      isoCode: 'VC',
      dialCode: '+1',
      currencyCode: 'XCD',
      usdExchangeRate: 2.7,
      localTransferAgents: ['Bank transfer', 'Cash pickup'],
    ),
    PaymentCountry(
      name: 'Trinidad and Tobago',
      region: 'North America',
      isoCode: 'TT',
      dialCode: '+1',
      currencyCode: 'TTD',
      usdExchangeRate: 6.8,
      localTransferAgents: ['WiPay', 'Bank transfer'],
    ),
    PaymentCountry(
      name: 'United States',
      region: 'North America',
      isoCode: 'US',
      dialCode: '+1',
      currencyCode: 'USD',
      usdExchangeRate: 1.0,
      localTransferAgents: ['Zelle', 'ACH', 'FedNow', 'Cash App'],
    ),
    PaymentCountry(
      name: 'USA',
      region: 'North America',
      isoCode: 'US',
      dialCode: '+1',
      currencyCode: 'USD',
      usdExchangeRate: 1.0,
      localTransferAgents: ['Zelle', 'ACH', 'FedNow', 'Cash App'],
    ),
  ];

  static List<PaymentCountry> countriesForRegion(String region) {
    return countries.where((country) => country.region == region).toList()
      ..sort((a, b) => a.name.compareTo(b.name));
  }

  static Map<String, List<PaymentCountry>> get regionalCountries {
    return {
      'Africa': countriesForRegion('Africa'),
      'North America': countriesForRegion('North America'),
    };
  }

  static List<PaymentMethodOption> methodsFor(PaymentCountry country) {
    return [
      const PaymentMethodOption(
        type: PaymentMethodType.card,
        label: 'Card',
        description: 'Visa or Mastercard',
        flutterwaveOption: 'card',
      ),
      if (country.supportsMobileMoney)
        PaymentMethodOption(
          type: PaymentMethodType.mobileMoney,
          label: country.localTransferLabel,
          description:
              'Pay using ${_formatProviderList(country.localTransferAgents)}',
          flutterwaveOption: 'mobilemoney',
        ),
      const PaymentMethodOption(
        type: PaymentMethodType.bankTransfer,
        label: 'Bank transfer',
        description: 'Supported local and international bank rails',
        flutterwaveOption: 'bank transfer',
      ),
    ];
  }

  static bool isAfricanCountry(PaymentCountry country) {
    return country.region == 'Africa';
  }

  static PaymentCountry? countryByName(String countryName) {
    for (final country in countries) {
      if (country.name == countryName) return country;
    }
    return null;
  }

  static List<String> transferAgentsForCountryName(String countryName) {
    return countryByName(countryName)?.localTransferAgents ?? const [];
  }

  static String defaultTransferMethodForCountryName(String countryName) {
    final agents = transferAgentsForCountryName(countryName);
    if (agents.isEmpty) return 'Bank transfer';
    return agents.first;
  }

  static String? isoCodeForCountryName(String countryName) {
    return countryByName(countryName)?.isoCode;
  }

  static String _formatProviderList(List<String> providers) {
    if (providers.isEmpty) return 'local transfer rails';
    if (providers.length == 1) return providers.first;
    if (providers.length == 2) return providers.join(' or ');

    return '${providers.take(providers.length - 1).join(', ')}, or '
        '${providers.last}';
  }
}
